import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import { styled, Flex } from "@kuma-ui/core";

const inter = Inter({ subsets: ["latin"] });

const ThisIsStyledComponent = styled.div`
  display: flex;
  justify-content: center;
  padding: 8px;
  color: white;
  background: black;
  @media (max-width: 500px) {
    color: blue;
  }
`;

const ThisIsStyledComponentTwo = styled(ThisIsStyledComponent)`
  color: blue;
`;

const ThisIsStyledComponentTree = styled(ThisIsStyledComponentTwo)`
  padding: 8px;
  background-color: #f00;
  color: white;
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KumaRegistry>
          <ThisIsStyledComponent>AAAAAAAAAAAAAAAAA</ThisIsStyledComponent>
          <ThisIsStyledComponentTwo>BBBBBBBBBBBB</ThisIsStyledComponentTwo>
          <ThisIsStyledComponentTree>CCcccccccccc</ThisIsStyledComponentTree>
          {children}
        </KumaRegistry>
      </body>
    </html>
  );
}
