import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import { styled } from "../../node_modules/@kuma-ui/core/dist/styled";

const inter = Inter({ subsets: ["latin"] });

export const ThisIsStyledComponent = styled.div`
  padding: 8px;
  color: white;
  background: black;
  @media (max-width: 500px) {
    color: blue;
  }
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KumaRegistry>
          {children}
          <ThisIsStyledComponent />
        </KumaRegistry>
      </body>
    </html>
  );
}
